import { AppBar, Toolbar, Typography } from '@mui/material'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position='sticky' elevation={0}>
          <Toolbar>
            <Typography variant='h6'>Personajes de Rick and Morty</Typography>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  )
}
